hystrix:
  image: verifynow/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
discovery:
  image: verifynow/discovery-microservice
  ports:
   - "8761:8761"
configserver:
  image: verifynow/config-microservice
  ports:
   - "8888:8888"
  links:
   - discovery
gateway:
  image: verifynow/api-gateway-microservice
  ports:
   - "10000:10000"
  links:
   - discovery
   - configserver
   - user
   - movie
   - recommendation
user:
  image: verifynow/users-microservice
  links:
   - discovery
   - configserver
movie:
  image: verifynow/movie-microservice
  links:
   - discovery
   - configserver
report:
  image: verifynow/report-service
  ports:
  - "9009:9009"
  links:
   - discovery
   - configserver
recommendation:
  image: verifynow/recommendation-microservice
  links:
   - discovery
   - configserver
moviesui:
  image: verifynow/movies-ui
  ports:
     - "9006:9006"
  links:
   - discovery
   - configserver